### ISSUE TITLE
【资源帖】Date对象及案例

### ISSUE THREAD

**Issue by zptcsoft** [BestACE/fed#429]
## Date对象资源
1.  阮一峰 [Date 对象](https://wangdoc.com/javascript/stdlib/date.html)
2. MDN  [Date对象](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date)
3. 课程[讲义](https://bestace.github.io/fed/ppt/publish/38.html)
4. Moment.js [官方网站](http://momentjs.cn/)

## Date对象案例
1.  [数字时钟](https://bestace.github.io/fed/ppt/demos/jsBase/clock.html)
2.  [模拟时钟](https://bestace.github.io/fed/ppt/demos/jsBase/clock2.html)
3. [倒计时时钟](https://codepen.io/whqet/pen/yxGWQQ)
4. [Vue.js实现的漂亮时钟](https://codepen.io/whqet/pen/NLeVeY)
5. [颜色背景时钟](https://codepen.io/guardian/pen/YXOZpR)
6. [canvas实现的环形时钟](https://codepen.io/motorlatitude/pen/uevDx)

**Comment by zptcsoft** [comment]
网页时钟效果收集 #326

**Comment by zptcsoft** [comment]
## 秒针的实现
```css
#clock {
	width: 300px;
	height: 300px;
	background: url(https://bestace.github.io/fed/ppt/demos/jsBase/img/clock.jpg);
	background-size: 100%;
	position: relative;
}

#sec {
	width: 2px;
	height: 100px;
	background-color: #f00;
	position: absolute;
	left: 150px;
	bottom: 150px;
	transform-origin: 50% bottom;
	/*transform: rotate(30deg);*/
}
```
```html
<div id="clock">
	<div id="sec"></div>
</div>
```
```javascript
var oSec = document.getElementById("sec");
function getNow() {
	now = new Date();
	var hour = now.getHours();
	var min = now.getMinutes();
	var sec = now.getSeconds();
	oSec.style.transform="rotate("+sec*6+"deg)";		
	setTimeout(getNow, 1000);
}
getNow();
```
